apiVersion: v1
kind: Service
metadata:
  name: scoring-service
  namespace: fraud-detection
spec:
  selector:
    app: scoring-service
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
