apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  namespace: fraud-detection
data:
  BOOTSTRAP_SERVERS: "kafka:29092"
  SCORING_URL: "http://scoring-service:5000/score"
  RISK_THRESHOLD_LOW: "0.60"
  RISK_THRESHOLD_HIGH: "0.85"
  RETRAIN_THRESHOLD: "500"
  CHECK_INTERVAL: "300"
  MODELS_DIR: "/models"
  FEEDBACK_BUFFER_PATH: "/data/feedback/feedback_buffer.jsonl"
