apiVersion: batch/v1
kind: Job
metadata:
  name: fraud-model-training
  namespace: fraud-detection
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: training
          image: fraud-training:latest
          args: ["--dataset", "/data/raw/creditcard.csv"]
          volumeMounts:
            - name: data
              mountPath: /data
            - name: models
              mountPath: /models
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc
